### ISSUE TITLE
[android浏览器]页面事件穿透问题处理_Android browser event cross issue

### ISSUE THREAD

**Issue by hite** [hite/generator-wpd#1]
问题描述；在安卓端页面如果给一个div使用overflow:auto,并设定一个固定高度，里面可以滚动的内容会发生事件穿透，点击其他区域，都会触发点击div里面的内容.
rain css的select控件在弹出的选择列表里面的列表会在点击ok，cancel的时候被点击到，如图:
![穿透](http://www.webdevelopmentmachine.com/blog/wp-content/uploads/2013/12/Screenshot_2013-12-21-23-06-30.png)

解决这个问题的方法是在按钮的外层div上加入一个不可见的div来挡住事件的穿透:
css:

``` css
.touchWrap{margin:0;padding:0;border:none;background:rgba(255,255,255,0.01); -webkit-tap-highlight-color:rgba(0,0,0,0);top:0px;left:0px;z-index:-1;}
```

js:

``` javascript
buttonsWrap.append('<div class="touchWrap posa fullw fullh"></div>');
```

via [raincss](http://www.webdevelopmentmachine.com/blog/%E5%AE%89%E5%8D%93%E6%B5%8F%E8%A7%88%E5%99%A8%E9%A1%B5%E9%9D%A2%E4%BA%8B%E4%BB%B6%E7%A9%BF%E9%80%8F%E9%97%AE%E9%A2%98%E5%A4%84%E7%90%86_android-browser-event-cross-issue/)

[另外的描述](http://www.chawenti.com/articles/10570.html)

WebApp事件穿透效应：在WebApp中，在页面转场或硬切换或弹框等界面变化的处理中，把初始界面触发界面变化事件的元素btnA相对屏幕的位置标为screenPoint，而切换的目标界面在screenPoint位置也存在一个元素btnB并绑定了事件处理，在一定情况下，当btnA被触发时，btnB也会被触发。这里将这种现象成为事件穿透效应。

说明：
1、第一位置——初始界面触发界面变化事件的元素btnA
2、第二位置——目标界面元素btnB

测试结果：
1、第一位置为touchstart/touchend事件，第二位置为touchstart/touchend事件，未触发透传
2、第一位置为touchstart/touchend事件，第二位置为click事件，触发透传
3、第一位置为touchstart/touchend事件，第二位置为Input元素，触发透传
4、第一位置为click事件，第二位置为touchstart/touchend事件，未触发透传
5、第一位置为click事件，第二位置为click事件，未触发透传

结论：
1、第一位置与第二位置使用相同类型(即：非click即touch)的事件
2、第二位置为input元素时，第一位置使用click事件

以上为初步测试结果，有待更进一步研究。
大家可以根据测试结果，修改代码并测试，如有问题，请及时反馈。
